spring.application.name=BookMyService
spring.datasource.url=jdbc:postgresql://localhost:5432/bookmyservice
spring.datasource.username=ayushkumar
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
